/**
 * Configuration File Generator
 *
 * Generates YAML configuration files from user choices and preset
 * definitions. Includes validation before writing to ensure all
 * generated configs are valid.
 */

import { writeFile } from "fs/promises";
import { dump } from "js-yaml";
import path from "path";
import type { LabcommitrConfig } from "../../../lib/config/types.js";
import { ConfigValidator } from "../../../lib/config/validator.js";

/**
 * Add header comment to YAML output
 * Provides context and documentation link for users
 */
function addHeader(yaml: string): string {
  return `# Labcommitr Configuration
# Generated by: lab init
# Edit this file to customize your commit workflow
# Documentation: https://github.com/labcatr/labcommitr#config

${yaml}`;
}

/**
 * Generate and write configuration file
 * Validates config before writing to prevent invalid output
 *
 * @param config - Complete configuration object
 * @param projectRoot - Path to project root directory
 * @returns Path to written config file
 */
export async function generateConfigFile(
  config: LabcommitrConfig,
  projectRoot: string,
): Promise<string> {
  // Validate config before writing
  const validator = new ConfigValidator();
  const validation = validator.validate(config);

  if (!validation.valid) {
    throw new Error(
      `Generated config failed validation: ${validation.errors[0].message}`,
    );
  }

  // Convert to YAML with formatting options
  const yaml = dump(config, {
    indent: 2,
    lineWidth: 80,
    noRefs: true,
  });

  // Add header comments
  const content = addHeader(yaml);

  // Write to file
  const configPath = path.join(projectRoot, ".labcommitr.config.yaml");
  await writeFile(configPath, content, "utf-8");

  return configPath;
}
