name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  changelog:
    name: Changelog PR or Release
    if: ${{ github.repository_owner == 'labcatr' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest 

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # Note: pnpm install after versioning is necessary to refresh lockfile
          version: pnpm run version
          publish: pnpm exec changeset publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.VOXEL_GITHUB_TOKEN }}
          # Needs access to publish to npm
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
